builds:
- binary: NAMEinator
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm
  goarm:
  - 6
  - 7
  ldflags: >
    -X main.VERSION={{.Version}}
    -X main.DateBuilt={{.Date}}
archive:
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - datasrc/*
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
