builds:
- main: ./main.go
  files:
  - datasrc/
  binary: NAMEinator
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm
  goarm:
  - 6
  - 7
  ldflags: >
    -X main.Version={{.Version}}
    -X main.DateBuilt={{.Date}}
  format_overrides:
    - goos: windows
      format: zip
archive:
  wrap_in_directory: true
  format: tar.gz
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"